### ISSUE TITLE
View Event Attribute is Deprecated

### ISSUE THREAD

**Issue by 0xahs** [MAX-POLKOVNIK/DroidInjector#8]
How to inject events, I am using  ViewEvent but is says that it is deprecated. Kindly tell the new way to do this.
![image](https://user-images.githubusercontent.com/38754480/42227317-ae1aeb24-7efa-11e8-816d-e09485e5ad57.png)

**Comment by 0xahs** [comment]
@MAX-POLKOVNIK  Kindly Suggest

**Comment by MAX-POLKOVNIK** [comment]
@AhmadHassanSahi Hello. Sorry for waiting. Yes, that feature is deprecated and will be removed in future. 
And there is few cons in support and using of this event subscription instead of direct subscription: 
1. Subscription to event take a lot of time in this way when app executing. Main goal of this component is reducing time of view injection. 
2. It's required a lot of parameters in attribute. 
3. It's hard to refactor. 
4. By default ReSharper will mark this method as unused if it will has private modifier. 
5. Compiler can remove event from class (if linking enabled). In that case we can't subscribe to event.

**Comment by MAX-POLKOVNIK** [comment]
So you should use direct subscription or setting listener.
